AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Language-Learning

  Language Learning Assistant using OpenAI, Lambda, and Streamlit


Globals:
  Function:
    Timeout: 30
    MemorySize: 2048


Resources:
  LanguageLearningBase:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: base/
      Handler: function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        LanguageFunctionAPI:
          Type: Api
          Properties:
            Path: '/base'
            Method: GET
            Auth:
              Authorizer: NONE

