AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Language-Learning

  Language Learning Assistant using OpenAI, Lambda, and Streamlit


Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Resources:
  functionLambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: base/
      Handler: function.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          API_KEY: {api-key}
      Architectures:
        - x86_64
      Events:
        lambdaFunctionAPI:
          Type: Api
          Properties:
            Path: '/base'
            Method: ANY
            Auth:
              Authorizer: NONE
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-1:{}
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-east-1:{}:log-group:/aws/lambda/base:*
